### ISSUE TITLE
关于数据集A和数据集B链接无法访问

### ISSUE THREAD

**Issue by WSQ57** [baiyanquan/HolisticRCATempData#1]
您好！我在尝试下载数据集A和B的原始数据时，发现您列出的链接目前已经无法访问，请问您是否能够提供其他下载渠道，万分感激！

**Comment by baiyanquan** [comment]
您好，关于数据集详情请使用您的常用工作邮箱联系[2011438@tongji.edu.cn](mailto:2011438@tongji.edu.cn)。

**Comment by WSQ57** [comment]
感谢作者给予的帮助，充分解答了我的疑问，我将关闭这个问题
